import Phaser from 'phaser';

/** Все спрайты нарисованы скриптом art/sprites.py и лежат в public/assets. */
const SPRITES = [
  'floor',
  'wall',
  'concrete',
  'asphalt',
  'lot',
  'grass',
  'wall_cap',
  'facade',
  'shopwin',
  'awning_small',
  'door_open',
  'door_half',
  'raindrop',
  'roof',
  'arrow',
  'think',
  'cross',
  'cat',
  'pigeon0',
  'pigeon1',
  'pigeon_fly',
  'light_cone',
  'light_spill',
  'mud',
  'ripple',
  'mop',
  'puddle_wet',
  'gondola',
  ...['bag', 'backpack'].flatMap((b) => ['', '_b', '_s'].map((v) => `${b}${v}`)),
  'stroller',
  'stroller_s',
  'dog0',
  'dog1',
  'dog_sit0',
  'dog_sit1',
  'flower',
  'icecream',
  'pumpkin',
  'bat0',
  'bat1',
  'tulips',
  'snowman',
  'floor_wood',
  'floor_checker',
  'floor_gold',
  'art_sunflowers',
  'art_sea',
  'art_cat',
  'rug',
  'plant_big',
  'neon',
  'aquarium',
  'scaffold',
  'confetti',
  'ac_unit',
  'skylight',
  'bus_stop',
  'bus',
  'bus_lights',
  'splash',
  'snowflake',
  'leaf',
  'umbrella',
  'xmas_tree',
  'snow_ground',
  'p_legs2_s',
  'shutter',
  'weeds',
  'bricks',
  'sand',
  'cone',
  'tire',
  'puddle',
  'floor2',
  'floor3',
  'candy_rack',
  'carts',
  ...['car_sedan', 'car_hatch', 'car_taxi', 'car_van', 'car_truck'].flatMap((k) => [k, `${k}_lights`]),
  'mat',
  'glow',
  'coin',
  'spark',
  'puff',
  'bubble_s',
  'stink',
  'trash_banana',
  'trash_cup',
  'vending',
  'pallet_water',
  'promo',
  'paving',
  'tree',
  'bush',
  'lamp',
  'bench',
  'bin',
  'fence_h',
  'fence_v',
  'for_rent',
  'awning',
  'car',
  'sign',
  'shelf',
  'shelf_front',
  'stand',
  'stand_front',
  'fridge',
  'fridge_front',
  'shadow_wide',
  'window',
  'clock',
  'counter',
  'wc',
  'door',
  'box',
  'rack',
  ...['bread', 'apples', 'potatoes', 'milk', 'meat'].map((id) => `crate_${id}`),
  'trash',
  'bubble',
  'pip',
  'bar',
  'item_bread',
  'item_apples',
  'item_potatoes',
  'item_milk',
  'item_meat',
  ...['bread', 'apples', 'potatoes', 'milk', 'meat'].flatMap((id) => [0, 1, 2].map((v) => `item_${id}_${v}`)),
  ...['p_skin', 'p_shirt', 'p_legs0', 'p_legs1', 'acc_apron', 'acc_vest'].flatMap((k) => [k, `${k}_b`, `${k}_s`]),
  ...['short', 'long', 'bun', 'cap', 'bald', 'ponytail', 'curly', 'beanie'].flatMap((h) => ['', '_b', '_s'].map((v) => `p_hair_${h}${v}`)),
  'acc_badge',
  'acc_tie',
  'acc_glasses',
  'emo_angry',
  'emo_heart',
  'emo_question',
  'shadow',
  'plant',
  'poster',
  'baskets',
];

export class BootScene extends Phaser.Scene {
  constructor() {
    super('boot');
  }

  preload(): void {
    for (const key of SPRITES) this.load.image(key, `assets/${key}.png`);
  }

  create(): void {
    this.scene.start('store');
  }
}
