import { PRODUCT_IDS } from '../game/economy';
import Phaser from 'phaser';
import { syncSave } from '../game/save';

/** Все спрайты нарисованы скриптом art/sprites.py и лежат в public/assets. */
const SPRITES = [
  'floor',
  'wall',
  'concrete',
  'asphalt',
  'lot',
  'grass',
  'wall_cap',
  'facade',
  'shopwin',
  'awning_small',
  'door_open',
  'door_half',
  'raindrop',
  'roof',
  'arrow',
  'think',
  'cross',
  'cat',
  'pigeon0',
  'pigeon1',
  'pigeon_fly',
  'light_cone',
  'light_spill',
  'mud',
  'ripple',
  'mop',
  'puddle_wet',
  'gondola',
  ...['bag', 'backpack'].flatMap((b) => ['', '_b', '_s'].map((v) => `${b}${v}`)),
  'stroller',
  'stroller_s',
  'dog0',
  'dog1',
  'dog_sit0',
  'dog_sit1',
  'flower',
  'icecream',
  'pumpkin',
  'bat0',
  'bat1',
  'tulips',
  'snowman',
  'bin0',
  'bin1',
  'bin2',
  'bin3',
  'bin_t1_0',
  'bin_t1_1',
  'bin_t1_2',
  'bin_t1_3',
  'bin_t2_0',
  'bin_t2_1',
  'bin_t2_2',
  'bin_t2_3',
  'bin_t3_0',
  'bin_t3_1',
  'bin_t3_2',
  'bin_t3_3',
  'trash_bag',
  'dumpster',
  'spill',
  'spill_pack',
  'ad_banner',
  'flyer',
  'fusebox',
  'leak',
  'wrench',
  'card_terminal',
  'kiosk', 'candy', 'coffee_machine', 'coffee_machine1', 'coffee_machine2', 'cup', 'oven', 'oven1', 'oven2', 'oven_bread', 'review_board', 'cat_walk0', 'cat_walk1', 'cat_sit', 'cat_basket', 'cat_pillow', 'cat_house', 'phone', 'bike', 'mouse0', 'mouse1', 'fair_stall', 'eco_label', 'pallet_jack', 'forklift', 'autostore', 'fan_base', 'fan_blades', 'ac_wall', 'facade_screen0', 'facade_screen1', 'cam', 'mat_grate', 'air_curtain', 'slot_empty', 'wh_floor', 'hazard', 'wh_sign', 'extinguisher',
  'floor_wood',
  'floor_checker',
  'floor_gold',
  'art_sunflowers',
  'art_sea',
  'art_cat',
  'rug',
  'plant_big',
  'neon',
  'aquarium',
  'scaffold',
  'confetti',
  'ac_unit',
  'skylight',
  'bus_stop',
  'bus',
  'bus_lights',
  'splash',
  'snowflake',
  'leaf',
  'umbrella',
  'xmas_tree',
  'snow_ground',
  'p_legs2_s',
  'shutter',
  'weeds',
  'bricks',
  'sand',
  'cone',
  'tire',
  'puddle',
  'floor2',
  'floor3',
  'candy_rack',
  'radio',
  'coffee_bar',
  'cafe_table',
  'baker_table',
  'bread_rack',
  'bread_tray',
  'carts',
  ...['car_sedan', 'car_hatch', 'car_taxi', 'car_van', 'car_truck'].flatMap((k) => [k, `${k}_lights`]),
  'mat',
  'glow',
  'coin',
  'spark',
  'puff',
  'bubble_s',
  'stink',
  'trash_banana',
  'trash_cup',
  'vending',
  'pallet_water',
  'promo',
  'paving',
  'tree',
  'bush',
  'lamp',
  'bench',
  'bin',
  'fence_h',
  'fence_v',
  'for_rent',
  'awning',
  'car',
  'sign',
  'shelf',
  'shelf_front',
  'stand',
  'stand_front',
  'fridge',
  'fridge_front',
  'drinks',
  'drinks_front',
  'chem',
  'chem_front',
  'shadow_wide',
  'window',
  'clock',
  'counter0',
  'counter1',
  'counter2',
  'counter3',
  'wc',
  'door',
  'box',
  'rack',
  ...PRODUCT_IDS.map((id) => `crate_${id}`),
  'trash',
  'bubble',
  'pip',
  'bar',
  ...PRODUCT_IDS.map((id) => `item_${id}`),
  ...PRODUCT_IDS.flatMap((id) => [0, 1, 2].map((v) => `item_${id}_${v}`)),
  ...['p_skin', 'p_shirt', 'p_legs0', 'p_legs1', 'acc_apron', 'acc_vest'].flatMap((k) => [k, `${k}_b`, `${k}_s`]),
  ...['short', 'long', 'bun', 'cap', 'bald', 'ponytail', 'curly', 'beanie'].flatMap((h) => ['', '_b', '_s'].map((v) => `p_hair_${h}${v}`)),
  'acc_badge',
  'acc_tie',
  'acc_glasses',
  'emo_angry',
  'emo_heart',
  'emo_question',
  'shadow',
  'plant',
  'poster',
  'baskets',
];

export class BootScene extends Phaser.Scene {
  constructor() {
    super('boot');
  }

  preload(): void {
    for (const key of SPRITES) this.load.image(key, `assets/${key}.png`);
  }

  create(): void {
    // Сначала сверить сохранение с облаком Telegram (не дольше пары секунд), потом — в магазин.
    const start = () => this.scene.isActive('boot') && this.scene.start('store');
    const timer = setTimeout(start, 4000);
    void syncSave().finally(() => {
      clearTimeout(timer);
      start();
    });
  }
}
